apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: crossplane-function-test
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XDeploy
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-test
