apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-team-apps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - git:
        directories:
          - path: env/*/*
        repoURL: 'https://github.com/eliihen/example-team-apps.git'
        revision: HEAD
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{ .path.basename }}-{{ index .path.segments 1 }}'
    spec:
      destination:
        namespace: '{{ index .path.segments 2 }}'
        name: '{{ index .path.segments 1 }}'
      project: example-team
      source:
        path: '{{.path.path}}'
        repoURL: 'https://github.com/eliihen/example-team-apps.git'
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/managed-by: argocd
            team: exampleteam
            pod-security.kubernetes.io/audit: restricted
            istio-injection: enabled
        automated:
          prune: false
          allowEmpty: true
          selfHeal: true
