apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - resources/function.yaml
  - resources/composition.yaml
  - resources/xrd.yaml
  - resources/xr.yaml

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    includeCRDs: true
    namespace: crossplane
    version: 1.15.2
