apiVersion: v2
name: helm-app
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mariadb
    version: 11.5.2
    repository: oci://registry-1.docker.io/bitnamicharts
