apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foo
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - image: ghcr.io/eliihen/remix-test@sha256:0eab78b2b6019026daeb60b383b55896542b7e5831e46080e5796fa53eb2333a
          name: nginx
